### ISSUE TITLE
Decide on else-if control structure

### ISSUE THREAD

**Issue by dirk** [dirk/hummingbird#21]
`elseif`, `else if`, `elsif`, `elif`, what do we want to do?

**Comment by ryngonzalez** [comment]
`else if` is my vote :+1:

**Comment by dirk** [comment]
Yeah I was leaning towards `else if` is well. Going to fool around in the grammar tomorrow to get it integrated and make sure common cases get parsed correctly.

Accepting syntaxes:

```js
/**/ } else if /**/ { /**/

/**/ }
else if /**/ { /**/

/**/ } else
if /**/ { /**/
```

Any other formattings of `else if` that you think we should test for?

**Comment by EvanHahn** [comment]
+1 for `else if`.

**Comment by dirk** [comment]
Closing now that #25 and #20 are merged, which together bring in else-if and else.
