### ISSUE TITLE
Implement basic closure syntax

### ISSUE THREAD

**Issue by dirk** [dirk/hummingbird#24]
`func () with (a, b) { ... }` defines a closing function that _only_ has access to the outer linkages `a` and `b`. The type-system will enforce this behavior and disallow any other closing of linkages into the function's scope.

**Comment by ryngonzalez** [comment]
The more I think about this about this, the more reluctant I am of creating a syntax for explicitly declaring the variables being closed over in a function. I can imagine function definitions that become incredibly unwieldy once we have type annotations for the args, type annotations for the return types, and _then_ the syntax for explicit closing.

**Comment by dirk** [comment]
Yeah, I think that's a *very valid* caution against. I think though that this concern should be taken as a strong impetus for us to ensure our type-system is good enough to obviate almost all need for explicit variable types or return types (ie. like ML).

**Comment by ryngonzalez** [comment]
Agreed :+1:
