### ISSUE TITLE
Why use this over TypeScript?

### ISSUE THREAD

**Issue by ryngonzalez** [dirk/hummingbird#3]
I think we should be able to explain why this would be superior to TypeScript (and if it isn't, try to determine how we can improve on what TypeScript and AtScript already provide).

**Comment by EvanHahn** [comment]
The interop with multiple languages (discussed in #17) seems super cool to me. Imagine a language that'd let you use a Python library and a JavaScript library—I think that's a big selling point.

Seems wildly difficult (and arguably already exists with things like Bash) and might stray from the vision y'all have for the language. But might be cool!
